// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODmYdnuFySEbIvVmxzXZOvGfzHL7hm04',
    appId: '1:189833283931:web:8585653ac8a9d69378b27e',
    messagingSenderId: '189833283931',
    projectId: 'expense-tracker-47995',
    authDomain: 'expense-tracker-47995.firebaseapp.com',
    storageBucket: 'expense-tracker-47995.firebasestorage.app',
    measurementId: 'G-P33JP4SC04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0CsXcWs_BVut4xbczGmn0ks6PrsTfjD0',
    appId: '1:189833283931:android:7042ca5b9db984d278b27e',
    messagingSenderId: '189833283931',
    projectId: 'expense-tracker-47995',
    storageBucket: 'expense-tracker-47995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4L4qONAGkNdujnFG6o30YlvHQdkUSzOM',
    appId: '1:189833283931:ios:17c7e686c8c82ddb78b27e',
    messagingSenderId: '189833283931',
    projectId: 'expense-tracker-47995',
    storageBucket: 'expense-tracker-47995.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4L4qONAGkNdujnFG6o30YlvHQdkUSzOM',
    appId: '1:189833283931:ios:17c7e686c8c82ddb78b27e',
    messagingSenderId: '189833283931',
    projectId: 'expense-tracker-47995',
    storageBucket: 'expense-tracker-47995.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
